name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # Step 4: Run flake8 and save the report
      - name: Run flake8
        run: flake8 src/ --output-file=flake8-report.txt || true

      # Step 5: Upload flake8 report as an artifact
      - name: Upload flake8 report
        uses: actions/upload-artifact@v3
        with:
          name: flake8-report
          path: flake8-report.txt
